# -*- coding: utf-8 -*-
"""card game!.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTELjYDK8WcGRBJunapaQEhswU6t68-l
"""

import random
card={"雑魚1":1,"雑魚2":1,"雑魚3":1,"雑魚4":1,"普通5":2,"普通6":2,"最強":20,"無敵":100}

cardlist=list(card.keys())
#print(cardlist)
random.shuffle(cardlist)
def drawcard():
  draw=random.choice(cardlist)
  player.append(draw)
def pg():
  global damege,playerhp
  playergard=input("ガードしますか(y/n):")
  print(f"CPUのだしたものは{cputurn}")
  if playergard=="n":
    playerhp=playerhp-damege
    print(f"CPUのだしたものは{cputurn}")
    print(f"CPUから{damege}くらってしまった")
    print(f"PLAYERのHPは{playerhp}")
  elif playergard=="y":
    gard=input("どれでガードしますか:")
    ggard=card[gard]
    damege=damege-ggard
    if damege<=0:
      damege=0
      print(f"CPUのだしたものは{cputurn}")
      print(f"CPUから{damege}くらってしまった")
      print(f"PLAYERのHPは{playerhp}")
    else:
      playerhp=playerhp-damege
      print(f"CPUのだしたものは{cputurn}")
      print(f"CPUから{damege}くらってしまった")
      print(f"PLAYERのHPは{playerhp}")

player=cardlist[::2]
cpu=cardlist[1::2]
playerhp=10
cpuhp=10
#print(f"あなたの手札：{player}")
#print(cpu)
while True:
  print(f"あなたの手札：{player}")
  playerturn=input("攻撃で使いたいカードを選んでね:")

  if playerturn in player:
    damege=card[playerturn]
    d=drawcard()
    player.remove(playerturn)
    print(player)
    cpugard=random.choice(cpu)
    print(f"CPUは{cpugard}を使ってガードした！")
    cpug=card[cpugard]
    damege=damege-cpug
    if damege<=0:
      damege=0
      cpuhp=cpuhp-damege
      print(f"CPUのHPは{cpuhp}")
      print("-"*30)
    else:
      cpuhp=cpuhp-damege
      print(f"CPUのHPは{cpuhp}")
      print("-"*30)
    if cpuhp<=0:
      print("YOU WIN")
      break
  else:
    print("そんなカードはない")

  print("cpuのターン")
  cputurn=random.choice(cpu)
  damege=card[cputurn]

  ppgg=pg()

  print("="*30)
  if playerhp<=0:
    print("CPU WIN")
    break