# -*- coding: utf-8 -*-
"""card game!.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTELjYDK8WcGRBJunapaQEhswU6t68-l
"""

import random
import sys
card = {
    "銅のこん棒": 1,
    "パンチ": 3,
    "ハチェット": 4,
    "鎖ガマ": 5,
    "硬いつち": 6,
    "なぎなたクラシック": 7,
    "ファイナル牙": 8,
    "パワーハルベルト": 9,
    "神の剣": 15,
    "巨人のこん棒": 20,
    "ほむら巻き": 4,
    "氷結ハンマー": 4,
    "夢の木づち": 4,
    "キラーフォーク": 5,
    "死神のカマ": 10,
    "火の玉": 2,
    "氷": 4,
    "大木": 6,
    "岩": 8,
    "炎": 10,
    "滝": 25,
}

card_defense = {
    "木の盾": 1,
    "皮の盾": 2,
    "おなべのふた": 2,
    "旅人の服": 2,
    "皮のよろい": 3,
    "鉄の盾": 4,
    "鉄のよろい": 5,
    "鋼の盾": 6,
    "こうらの盾": 7,
    "騎士のよろい": 8,
    "大木の盾": 10,
    "オーロラの盾": 10,
    "精霊の頭巾": 10,
    "鬼のよろい": 12,
    "神の盾": 15,
    }

cardlist=list(card.keys())
dcardlist=list(card_defense.keys())
random.shuffle(cardlist)
random.shuffle(dcardlist)
#カードを引くやつ
def drawcard():
  draw=random.choice(cardlist)
  player.append(draw)
#playerのガード
def pg():
  global damege,playerhp
  playergard=input("ガードしますか(y/n):")
  print(f"CPUのだしたものは{cputurn}")
  if playergard=="n":
    playerhp=playerhp-damege
    print(f"CPUから{damege}くらってしまった")
    print(f"PLAYERのHPは{playerhp}")
  elif playergard=="y":
    print(f"ディフェンスカード:{dplayer}")
    gard=input("どれでガードしますか:")
    dplayer.remove(gard)
    a=random.choice(dcardlist)
    dplayer.append(a)
    ggard=card_defense[gard]
    damege=damege-ggard
    if damege<=0:
      damege=0
      print(f"CPUのだしたものは{cputurn}")
      print(f"CPUから{damege}くらってしまった")
      print(f"PLAYERのHPは{playerhp}")
    else:
      playerhp=playerhp-damege
      print(f"CPUのだしたものは{cputurn}")
      print(f"CPUから{damege}くらってしまった")
      print(f"PLAYERのHPは{playerhp}")
#playerのターン
def pt():
  global cpuhp
  print(f"あなたの攻撃手札：{player}、防御手札{dplayer}")
  print(f"あなたのHP:{playerhp}")
  playerturn=(input("攻撃で使いたいカードを選んでね:"))

  if playerturn in player:
    damege=card[playerturn]
    d=drawcard()
    player.remove(playerturn)
    print(player)

    cpugard=random.choice(dcpu)
    print(f"CPUは{cpugard}を使ってガードした！")
    cpug=card_defense[cpugard]
    dcpu.remove(cpugard)
    b=random.choice(dcardlist)
    dcpu.append(b)
    damege=damege-cpug

    if damege<=0:
      damege=0
      cpuhp=cpuhp-damege
      print(f"CPUのHPは{cpuhp}")
      print("-"*30)
    else:
      cpuhp=cpuhp-damege
      print(f"CPUのHPは{cpuhp}")
      print("-"*30)
    if cpuhp<=0:
      print("YOU WIN")
      sys.exit()
  elif playerturn in dplayer:
    print("それは防御カードだ")
  else:
    print("そんなカードはない")

player=cardlist[0:5]
dplayer=dcardlist[0:4]
cpu=cardlist[6:11]
dcpu=dcardlist[5:9]
playerhp=10
cpuhp=10

while True:
  #playerのターンの関数召喚
  aaa=pt()

  print("cpuのターン")
  cputurn=random.choice(cpu)
  damege=card[cputurn]
  #playerのガードの関数の召喚
  ppgg=pg()

  print("="*30)
  if playerhp<=0:
    print("CPU WIN")
    break