# -*- coding: utf-8 -*-
"""card game!_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-lvuHA-LovlT0nZ9WWMHc1JUTJ1ookc
"""

import random
import sys
card = {
    "銅のこん棒": 1,
    "パンチ": 3,
    "ハチェット": 4,
    "鎖ガマ": 5,
    "硬いつち": 6,
    "なぎなたクラシック": 7,
    "ファイナル牙": 8,
    "パワーハルベルト": 9,
    "神の剣": 15,
    "巨人のこん棒": 20,
    "ほむら巻き": 4,
    "氷結ハンマー": 4,
    "夢の木づち": 4,
    "キラーフォーク": 5,
    "死神のカマ": 10,
}

card_defense = {
    "木の盾": 1,
    "皮の盾": 2,
    "おなべのふた": 2,
    "旅人の服": 2,
    "皮のよろい": 3,
    "鉄の盾": 4,
    "鉄のよろい": 5,
    "鋼の盾": 6,
    "こうらの盾": 7,
    "騎士のよろい": 8,
    "大木の盾": 10,
    "オーロラの盾": 10,
    "精霊の頭巾": 10,
    "鬼のよろい": 12,
    "神の盾": 15,
    }
kiseki={
    "火の玉": 2,
    "氷": 4,
    "大木": 6,
    "岩": 8,
    "炎": 10,
    "滝": 25
}

cardlist=list(card.keys())
dcardlist=list(card_defense.keys())
kisekilist=list(kiseki.keys())
random.shuffle(kisekilist)
random.shuffle(cardlist)
random.shuffle(dcardlist)
#cpuの計算
def keisan():
  global damege,cpuhp
  if damege<=0:
    damege=0
    cpuhp=cpuhp-damege
    print(f"CPUのHPは{cpuhp}")
    print("-"*30)
  else:
    cpuhp=cpuhp-damege
    print(f"CPUのHPは{cpuhp}")
    print("-"*30)
  if cpuhp<=0:
      print("YOU WIN")
      sys.exit()
#カードを引くやつ
def drawcard():
  draw=random.choice(cardlist)
  player.append(draw)
#playerのガード
def pg():
  global damege,playerhp
  playergard=input("ガードしますか(y/n):")
  cpupower=card[cputurn]
  print(f"CPUのだしたものは{cputurn}(攻撃力{cpupower})")
  if playergard=="n":
    playerhp=playerhp-damege
    print(f"CPUから{damege}くらってしまった")
    print(f"PLAYERのHPは{playerhp}")
  elif playergard=="y":
    for name in dplayer:
      gurad=card_defense[name]
      print(f"・{name}(防御力:{gurad})")
    gard=input("どれでガードしますか:")
    dplayer.remove(gard)
    a=random.choice(dcardlist)
    dplayer.append(a)
    ggard=card_defense[gard]
    damege=damege-ggard
    if damege<=0:
      damege=0
      #print(f"CPUのだしたものは{cputurn}")
      print(f"CPUから{damege}くらってしまった")
      print(f"PLAYERのHPは{playerhp}")
    else:
      playerhp=playerhp-damege
      #print(f"CPUのだしたものは{cputurn}")
      print(f"CPUから{damege}くらってしまった")
      print(f"PLAYERのHPは{playerhp}")
#playerのターン
def pt():
  global cpuhp,damege,playermp
  for name in player:
    power=card[name]
    print(f"  ・{name} (攻撃力: {power})")
  for name in pkiseki:
    kisekip=kiseki[name]
    print(f"奇跡:{pkiseki}(必要MP:{kisekip})")
  print(f"HP:{playerhp},MP:{playermp}")
  playerturn=(input("攻撃で使いたいカードを選んでね:"))

  if playerturn in player:

    damege=card[playerturn]
    d=drawcard()
    player.remove(playerturn)
    print(player)
    cpugard=random.choice(dcpu)
    cpug=card_defense[cpugard]
    print(f"CPUは{cpugard}を使ってガードした！(防御力{cpug})")
    dcpu.remove(cpugard)
    b=random.choice(dcardlist)
    dcpu.append(b)
    damege=damege-cpug
    keisan()

  elif playerturn in dplayer:
    print("それは防御カードだ")

  elif playerturn in pkiseki:
    MP=kiseki[playerturn]
    if playermp<=MP:
      print("MPが足りません！")

    else:
      cpugard=random.choice(dcpu)
      damege1=kiseki[playerturn]
      cpug=card_defense[cpugard]
      print(f"CPUは{cpugard}を使ってガードした！(防御力{cpug})")
      dcpu.remove(cpugard)
      b=random.choice(dcardlist)
      dcpu.append(b)
      damege=damege1-cpug
      playermp=playermp-damege1
      print(f"残りのMP:{playermp}")
      keisan()

  else:
    print("そんなカードはない")

player=cardlist[0:5]
dplayer=dcardlist[0:4]
pkiseki=kisekilist[0:1]
cpu=cardlist[6:11]
dcpu=dcardlist[5:9]
ckiseki=kisekilist[2:3]
playerhp=40
cpuhp=40
playermp=10
cpump=10
#print(pkiseki)
while True:
  #playerのターンの関数召喚
  pt()
  #print("-"*30)あ
  print("cpuのターン")
  cputurn=random.choice(cpu)
  damege=card[cputurn]

  #playerのガードの関数の召喚
  pg()

  print("="*30)
  if playerhp<=0:
    print("CPU WIN")
    break