# -*- coding: utf-8 -*-
"""stone_taking_game!_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ic0eZQwsBH0u0-rbbQk0YdTXdHFfRYxX
"""

import random
count=0
print("Stone taking Game!")
#enter the number of stone
totalstone=int(input("please enter the number the stone!--->"))
print(f"the number of stones {totalstone}")
print("-"*50)
#color
red='\033[31m'
yello='\033[33m'
green='\033[32m'
end='\033[0m'
while True:
  count=count+1
  print(f"Turn {count}")
  #player select the between 1,3
  a=int(input("1P select the between 1 and 3 --->"))

  if a<=3:
    totalstone=totalstone-a
    print(f"Number of remaining stones {red}{totalstone}{end}")

    if totalstone <= 0:
      print(red+"Your lose"+end)
      break
#cpus turn
  b=random.randint(1,3)

  if b<=3:
    totalstone=totalstone-b
    print(f"The number generated by the CPU {yello}{b}{end}")
    print(f"Number of remaining stones {green}{totalstone}{end}")
    print("-"*50)

    if totalstone<=0:
      print(green+"Your Win!!"+end)
      break

  elif a>=4:
    print("select the between 1 and 3")