# -*- coding: utf-8 -*-
"""card_game!(神の領域)_v5ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-lvuHA-LovlT0nZ9WWMHc1JUTJ1ookc
"""

import random
import sys
card = {
    "銅のこん棒": 1,
    "パンチ": 3,
    "ハチェット": 4,
    "鎖ガマ": 5,
    "硬いつち": 6,
    "なぎなたクラシック": 7,
    "ファイナル牙": 8,
    "パワーハルベルト": 9,
    "神の剣": 15,
    "巨人のこん棒": 20,
    "ほむら巻き": 4,
    "氷結ハンマー": 4,
    "夢の木づち": 4,
    "キラーフォーク": 5,
    "死神のカマ": 10,
}

card_defense = {
    "木の盾": 1,
    "皮の盾": 2,
    "おなべのふた": 2,
    "旅人の服": 2,
    "皮のよろい": 3,
    "鉄の盾": 4,
    "鉄のよろい": 5,
    "鋼の盾": 6,
    "こうらの盾": 7,
    "騎士のよろい": 8,
    "大木の盾": 10,
    "オーロラの盾": 10,
    "精霊の頭巾": 10,
    "鬼のよろい": 12,
    "神の盾": 15,
    }
kiseki={
    "火の玉": 2,
    "氷": 4,
    "大木": 6,
    "岩": 8,
    "炎": 10,
    "滝": 25
}

HPkaihuku={
    "スマイルのしずく":5,
    "ハートのしずく":10,
    "ロマンスウォーター":15,
    "天の川の水":20
}
MPkaihuku={
    "スマイルの花":5,
    "ハートの花":10,
    "ロマンスの香木":15,
    "天国草":20
}

HPlist=list(HPkaihuku.keys())
MPlist=list(MPkaihuku.keys())

def kaihukutati():
  global HPlist,MPlist
  a=random.randint(1,5)
  if a==1:
    random.shuffle(HPlist)
    player=HPlist[0]
    return player
  elif a==2:
    random.shuffle(MPlist)
    player=MPlist[0]
    return player
  else:
    player="なし"
    return player

cardlist=list(card.keys())
dcardlist=list(card_defense.keys())
kisekilist=list(kiseki.keys())
random.shuffle(kisekilist)
random.shuffle(cardlist)
random.shuffle(dcardlist)

#cpuの計算
def keisan():
  global damege,cpuhp
  if damege<=0:
    damege=0
    cpuhp=cpuhp-damege
    print(f"CPUのHPは{cpuhp}")
    print("-"*30)
  else:
    cpuhp=cpuhp-damege
    print(f"CPUのHPは{cpuhp}")
    print("-"*30)
  if cpuhp<=0:
      print("YOU WIN")
      sys.exit()
#カードを引くやつ
def drawcard():
  draw=random.choice(cardlist)
  player.append(draw)

def heelcpu():
  global cpuhp,cpump,cputurn,l,cpupower
  heel=kaihukutati()
  if heel in HPkaihuku:
    heelpower=HPkaihuku[heel]
    cpuhp=cpuhp+heelpower
    print(f"CPUは{heel}をつかって、{heelpower}回復した（CPUHP:{cpuhp}）")
    print("="*30)
  elif heel in MPkaihuku:
    heelpower=MPkaihuku[heel]
    cpump=cpump+heelpower
    print(f"CPUは{heel}をつかって、{heelpower}回復した（CPUMP:{cpump}）")
    print("="*30)
  else:
    cputurn=random.choice(cpu)
    damege=card[cputurn]
    print(f"cpuの出したものは{cputurn}(攻撃力:{damege})")
    #playerのガードの関数の召喚
    pg()
#playerのガード
def pg():
  global damege,playerhp,l,cputurn

  for name in ckiseki:
    MP=kiseki[name]
  playergard=input("ガードしますか(y/n):")

  if l==1:
    cpupower=card[cputurn]
    print(f"CPUのだしたものは{cputurn}(攻撃力{cpupower})")
  elif l==2:
    cpupower=kiseki[cputurn]
    print(f"CPUのだしたものは{cputurn}(攻撃力{cpupower})")
  while True:
    if playergard=="n":
      playerhp=playerhp-damege
      print(f"CPUから{damege}くらってしまった")
      print(f"PLAYERのHPは{playerhp}")
      break
    elif playergard=="y":
      for name in dplayer:
        gurad=card_defense[name]
        print(f"・{name}(防御力:{gurad})")
      gard=input("どれでガードしますか:")
      dplayer.remove(gard)
      a=random.choice(dcardlist)
      dplayer.append(a)
      ggard=card_defense[gard]
      damege=damege-ggard
      if damege<=0:
        damege=0
      #print(f"CPUのだしたものは{cputurn}")
        print(f"CPUから{damege}くらってしまった")
        print(f"PLAYERのHPは{playerhp}")
        break
      else:
        playerhp=playerhp-damege
        #print(f"CPUのだしたものは{cputurn}")
        print(f"CPUから{damege}くらってしまった")
        print(f"PLAYERのHPは{playerhp}")
        break
#playerのターン
def pt():
  global cpuhp,damege,playermp,playerhp,aaa
  while True:

    if aaa in HPlist:
      power1=HPkaihuku[aaa]
      print(f"  ・{aaa}(回復量{power1})")
    elif aaa in MPlist:
      power1=MPkaihuku[aaa]
      print(f"  ・{aaa}(回復量{power1})")
    else:
      print("なし")

    for name in player:
      power=card[name]
      print(f"  ・{name} (攻撃力: {power})")
    for name in pkiseki:
      kisekip=kiseki[name]
      print(f"奇跡:{pkiseki}(必要MP:{kisekip})")
    print(f"HP:{playerhp},MP:{playermp}")
    playerturn=(input("攻撃で使いたいカードを選んでね:"))

    if playerturn in player:

      damege=card[playerturn]
      d=drawcard()
      player.remove(playerturn)
      print(player)
      cpugard=random.choice(dcpu)
      cpug=card_defense[cpugard]
      print(f"CPUは{cpugard}を使ってガードした！(防御力{cpug})")
      dcpu.remove(cpugard)
      b=random.choice(dcardlist)
      dcpu.append(b)
      damege=damege-cpug
      keisan()
      break

    elif playerturn in dplayer:
      print("-"*30)
      print("それは防御カードだ")

    elif playerturn in HPkaihuku:
      playerhp=playerhp+power1
      print(f"HPが{playerhp}になった")
      #drawcard()
      break

    elif playerturn in MPkaihuku:
      playermp=playermp+power1
      print(f"MPが{playermp}になった")
      #drawcard()
      break

    elif playerturn in pkiseki:
      MP=kiseki[playerturn]
      if playermp<MP:
        print("MPが足りません！")

      else:
        cpugard=random.choice(dcpu)
        damege1=kiseki[playerturn]
        cpug=card_defense[cpugard]
        print(f"CPUは{cpugard}を使ってガードした！(防御力{cpug})")
        dcpu.remove(cpugard)
        b=random.choice(dcardlist)
        dcpu.append(b)
        damege=damege1-cpug
        playermp=playermp-MP
        print(f"残りのMP:{playermp}")
        drawcard()
        keisan()
        break

    else:
      print("-"*30)
      print("そんなカードはない")

player=cardlist[0:5]
dplayer=dcardlist[0:4]
pkiseki=kisekilist[0:1]
cpu=cardlist[6:11]
dcpu=dcardlist[5:9]
ckiseki=kisekilist[2:3]
playerhp=40
cpuhp=40
playermp=10
cpump=10
#print(pkiseki)


while True:
  print("="*10,"playのしかた","="*10)
  print("(1)回復アイテムは１ターンで消えるか、変わってしまいます！")
  print("(2)先攻はあなたで、後攻はCPUです！")
  print("(3)回復アイテムをつかうと、HPかMPを回復できます！")
  print("(4)y/nなどの選択は半角で！")
  start=input("準備はいいですか？:(y/n)")
  if start=="y":
    print("="*30)
    break
  else:
    print("もう一回説明する")

while True:
  aaa=kaihukutati()
  #playerのターンの関数召喚
  pt()
  #print("-"*30)あ
  print("cpuのターン")
  l=random.randint(1,3)

  for name in ckiseki:
    aiu=kiseki[name]
  if l==1:
    cputurn=random.choice(cpu)
    damege=card[cputurn]
    #playerのガードの関数の召喚
    pg()
  elif l==2:
    if aiu<cpump:
      cputurn=random.choice(ckiseki)
      damege=kiseki[cputurn]
      pg()
    elif aiu>cpump:
      cputurn=random.choice(cpu)
      damege=card[cputurn]
  elif l==3:
    heelcpu()
  print("="*30)
  if playerhp<=0:
    print("CPU WIN")
    break

