# -*- coding: utf-8 -*-
"""Guess the number! ver1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnKDSrtBItgjQrJs5dKX2r0NlKHR1xsJ
"""

import random
a=random.randint(1,100)
print("Guess the number!")
count=0
while True:
  count=count+1
  b=int(input("Guess the number"))
  if a==b:
    print(f"It's a success on the {count} try!")
    break
  elif a>b:
    print("bigger")
  elif a<b:
    print("smaller")