# -*- coding: utf-8 -*-
"""pandasの練習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrUJDIhcAGfcj-xluz44ZkcJ6GNQm9_9
"""

import pandas as pd
import random

players={
    "NAME":["player","sub_attacker"],
    "ATK":[10,5],
    "hp":[10,20]
}

enemys={
    "NAME":["goblin","slime"],
    "ATK":[5,2],
    "hp":[6,5]
}

df=pd.DataFrame(players)
edf=pd.DataFrame(enemys)
print(df)
print("="*30)
pt=int(input())

if pt==1:
  a=int(input(f"どっちを攻撃する？{edf.loc[0,"NAME"]}(1),{edf.loc[1,"NAME"]}(2)"))
  a=a-1

  damege=df.loc[0,"ATK"]
  edf.loc[a,"hp"]=edf.loc[a,"hp"]-damege

  if edf.loc[a,"hp"]<=0:
    edf.loc[a,"hp"]=0

  print(f"{damege}の攻撃をして、{edf.loc[a,"NAME"]}のHPが{edf.loc[a,"hp"]}になった")