# -*- coding: utf-8 -*-
"""サイコロゲーム.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15H4a2MmooOgq56EE9zMggZMAe88fZBSv
"""

import random
suika_x=random.randint(1,10)
suika_y=random.randint(1,10)
#suika_x=4
#suika_y=4

player_x=random.randint(1,10)
player_y=random.randint(1,10)
#player_x=2
#player_y=2
print(f"スイカの座標は:{suika_x,suika_y}")


print("＝＝＝スイカ割りゲーム＝＝＝")
while True:
  print(f"今のあなたのところは{player_x,player_y}")
  a=input("player_x(w:+1/s:-1)--->")
  b=input("player_y(a:+1/d:-1)--->")

  if a=="w":
    player_x=player_x+1
  elif a=="s":
    player_x=player_x-1
  if b=="a":
    player_y=player_y+1
  elif b=="d":
    player_y=player_y-1

  if suika_x-2<=player_x<=suika_x+2 and suika_y-2<=player_y<=suika_y+2:
    print("かなりちかいです！")
  elif suika_x-4<=player_x<=suika_x+4 and suika_y-4<=player_y<=suika_y+4:
    print("まあまあちかいです！")
  else:
    print("遠いです")

  print(f"{player_x,player_y}に移動しました")

  if player_x==suika_x and player_y==suika_y:
    print("すいかをわりました！")
    break