# -*- coding: utf-8 -*-
"""分析AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xd6Q2dlkEgBOJJq3v5Cx6K478qAw23z
"""

import numpy
from sklearn.linear_model import LinearRegression as LR

X=numpy.array([[10],[20],[30],[40],[50]])
y=numpy.array([122,232,344,445,535])

model=LR()
model.fit(X,y)

A=numpy.array([[15]])

B=model.predict(A)

print(f"{B[0]:.2f}")