# -*- coding: utf-8 -*-
"""繰り返し処理の練習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KwOxMFwFa4IwfhAuF3rWlJps__gLmiv
"""

total=0
i=1
while i <= 50:
  total += i
  i +=1
print(total)

count=6
while count>1:
  count-=1
  print(count)
print("fire!")

numbers=[3, 12, 7, 24, 35, 42, 8, 15]

for num in numbers:
  if num % 2==0:
    print(num)

import random
while True:
  a=random.randint(1,5)
  b=int(input())
  if a==b:
    print("ドカン")
    break
  else:
    print("セーフ")

import random
count=0
cpu=0
A=["グー","チョキ","パー"]
a=random.choice(A)

for i in range(3):
  b=input()
  if a==b:
    print("あいこ")
  elif a=="グー" and b=="チョキ" or a=="パー"and b=="グー" or a=="チョキ"and b=="パー":
    print("負け")
    cpu=cpu+1
  else:
    print("勝ち")
    count=count+1
  print(f"cpuの手は{a}")
print(f"あなたの勝利回数は{count}で,cpuの勝利回数は{cpu}でした！")