# -*- coding: utf-8 -*-
"""classとかselfとか.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Q0DpBVQkrcZTaL0hVcj90a4cniFPRK1
"""

import random

class Omikuzi:
  def __init__(self, name):
    self.name=name
    self.result=["大吉", "中吉", "小吉", "凶"]

  def draw(self):
    a=random.choice(self.result)
    print(f"{self.name}さんの運勢は{a}です")

user1=Omikuzi("oda")
user1.draw()

user2=Omikuzi("oda2")
user2.draw()

import random as rd
class player:
  def __init__ (self,name):
    self.name=name
    self.hp=100
  def stats(self):
    print(f"{self.name}でHP{self.hp}")
  def take_damege(self):
    self.hp=self.hp-damege
    print(f"{self.name}は{damege}をうけた")
playrename=input("whats your name:")
p1=player(playrename)
p1.stats()
damege=rd.randint(1,100)
#damege=(30)
p1.take_damege()
p1.stats()