# -*- coding: utf-8 -*-
"""pandasの練習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrUJDIhcAGfcj-xluz44ZkcJ6GNQm9_9
"""

import pandas as pd
import random

players={
    "NAME":["player","sub_attacker"],
    "ATK":[5,7],
    "MP":[0,5],
    "hp":[10,20]
}

enemys={
    "NAME":["goblin","slime"],
    "ATK":[5,2],
    "hp":[10,10]
}

df=pd.DataFrame(players)
edf=pd.DataFrame(enemys)
print(df)
print("="*30)

while True:
  if len(df)==0:
    print("yourlose")
    break

  for i in range(len(df)):
    print(f"{i+1}:役職:{df.loc[i,"NAME"]},ATK:{df.loc[i,"ATK"]},HP:{df.loc[i,"hp"]}")
  pt=int(input("誰で攻撃しますか？:"))
  pt=pt-1

  for i in range(len(edf)):
    print(f"{i+1}{edf.loc[i,"NAME"]},HP:{edf.loc[i,"hp"]}")
  a=int(input(f"どっちを攻撃する？:"))
  a=a-1

  damege=df.loc[pt,"ATK"]
  edf.loc[a,"hp"]=edf.loc[a,"hp"]-damege

  if edf.loc[a,"hp"]<=0:
    edf.loc[a,"hp"]=0

  print(f"{damege}の攻撃をして、{edf.loc[a,"NAME"]}のHPが{edf.loc[a,"hp"]}になった")
  print("-"*30)

  edf = edf[edf["hp"] > 0]
  edf = edf.reset_index(drop=True)

  if len(edf)==0:
    print("You Win")
    break
  else:
    select_player=random.randint(0,len(df)-1)
    select_enemy=random.randint(0,len(edf)-1)

    damege=edf.loc[select_enemy,"ATK"]
    df.loc[select_player,"hp"]=df.loc[select_player,"hp"]-damege

    print(f"{edf.loc[select_enemy,"NAME"]}から{damege}の攻撃をされた！、{df.loc[select_player,"NAME"]}のHPが{df.loc[select_player,"hp"]}になった")
    print("-"*30)

    df = df[df["hp"] > 0]
    df = df.reset_index(drop=True)