# -*- coding: utf-8 -*-
"""black juck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buCJSV26yBvHiqCfXTdI5s4FCbLj3Du6
"""

import random
import sys
def draw_card():
  return random.randint(1,10)

def status(name,hand):
  total=sum(hand)
  print(f"{name}{hand}（total:{total}）")
  return total

def main():
  print("black juck!!")

  player=[draw_card(), draw_card()]
  cpu=[draw_card(),draw_card()]

  while True:
    playrtotal=status("my_card",player)

    if playrtotal<=21:
      a=input("Would you like to draw again?--->y/n")
      if a=="y":
        new=draw_card()
        player.append(new)
        print(new)
      elif a=="n":
        break

    elif playrtotal>21:
      print("lose")
      sys.exit()

  while True:
    cputotal=status("cpu",cpu)

    if cputotal<15:
      newcpu=draw_card()
      cpu.append(newcpu)
      print(newcpu)
      if cputotal>21:
        print("win")
        break

    elif cputotal>=15:
      break



  if 15<=cputotal<=21 and playrtotal<cputotal:
    print("lose")

  elif 15<=cputotal<=21 and playrtotal>cputotal:
    print("win")

  else:
    print("draw")

if __name__=="__main__":
  main()