# -*- coding: utf-8 -*-
"""さいころRPG2.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHC50sO28eOQw1sYFRHEKbeys6b8p95h
"""

import random
import sys
count=1
money=0
myitem="なし"
monster=10
#基本となるさいころを振るところ
def rolldice():
  return random.randint(1,6)
#モンスターのHP処理
def monsterHP():
  global monster
  dice=rolldice()
  monster=monster*dice
  return monster

#攻撃力を計算するとこ
def attack(name,power):
  dice=rolldice()
  damege=power+dice
  return damege
#死んだとき（playerhp<=0）の処理
def hantei(playerhp):
  if playerhp<=0:
    print("あなたは死んでしまった。")
    life=input("生き返りますか？(y/n):")
    if life=="y":
      print("生き返った！")
    elif life=="n":
      print("死んだ")
      sys.exit()
  return playerhp
#アイテムを渡すときの処理
def giveitem():
  item=rolldice()
  if 1<=item<=3:
    print("超回復のポーションを手に入れた！")
    return "portion"
  else:
    print("めっちゃ強い剣をゲットした！")
    return "sord"
#お店
def shop():
  global money, myitem
  zxc=input("買い物しますか？:y/n")
  if zxc=="y":
    buy=int(input("(1)MP回復薬:10円,(2)HP回復薬:10円,(3)攻撃力の粉:20円"))
    if buy==1 and money>=10:
      money=money-10
      print(f"HP:{playerhp},MP:{MP},基礎攻撃力:{baise},アイテム:{myitem},お金:{money}")
      myitem="MP回復薬"
      return
    elif buy==2 and money>=10:
      money=money-10
      print(f"HP:{playerhp},MP:{MP},基礎攻撃力:{baise},アイテム:{myitem},お金:{money}")
      myitem="HP回復薬"
      return
    elif buy==3 and money>=20:
      money=money-20
      print(f"HP:{playerhp},MP:{MP},基礎攻撃力:{baise},アイテム:{myitem},お金:{money}")
      myitem="攻撃力の粉"
      return
#敵のターン
def ememyturn():
  global playerhp
  print("敵のターン")
  damege=attack("敵",2)
  print(f"敵の攻撃は{damege}")
  playerhp=playerhp-damege
  print(f"あなたのHPは{playerhp}")
  print("="*30)
  if playerhp<=0:
    aiue=hantei(playerhp)
    print(aiue)
#全部くくったやつ
def allturn():
  global myitem,baise,mos1,playerhp,count,MP,money,mos1#,rocovary
  while True:
    print(f"HP:{playerhp},MP:{MP},基礎攻撃力:{baise},アイテム:s1{myitem},お金:{money}")

    playerturn=int(input(f"何をする？（戦う(1)、回復(2)、逃げる(3)、アイテム(4)持ってるもの:{myitem} ）"))
    if playerturn==4 and myitem=="sord"or myitem=="攻撃力の粉":
      print(myitem)
      baise=baise+20
      print(f"基礎攻撃力{baise}にアップ！")
      myitem="なし"
    elif playerturn==4 and myitem=="portion"or myitem=="HP回復薬":
      print(myitem)
      playerhp=playerhp+35
      print(f"HPが{playerhp}に回復！")
      myitem="なし"
    elif playerturn==4 and myitem=="MP回復薬":
      print(myitem)
      MP=MP+20
      print(f"MPが{MP}にアップ！")
      myitem="なし"

    elif playerturn==4 and myitem=="なし":
      print("アイテムを持っていません！")

    elif playerturn==3:
      nigeru=rolldice()
      if 1<=nigeru<=3:
        print("逃げれなかった")
      else:
        print("逃げ切れた")
        print("="*30)
        break
    elif playerturn==2:
      rocovary=rolldice()
      if playerhp<=0:
        playerhp=playerhp+5*rocovary
      else:
        playerhp=playerhp+3+rocovary
        print(f"HPが{playerhp}になった!")

    elif playerturn==1:
      atk=int(input("物理攻撃(1),魔法攻撃(2)"))
      if atk==1:
        damege=attack("player",baise)
        print(f"{damege}の攻撃をした！")
        mos1=mos1-damege
      elif atk==2:
        if MP>3:
          MP=MP-3
          damege=attack("player",baise)
          print(f"{damege*2}の攻撃をした！")
          mos1=mos1-(damege*2)
          print(f"残りのMPは{MP}です")
        else:
          print("MPが足りません！")
      print(f"敵のHPは{mos1}")
      if mos1<=0:
        print("あなたの勝利！")
        print("="*30)
        count=count+1
        print(f"レベルが{count}に上がりました")
        baise=baise+rolldice()
        print(f"あなたの基礎攻撃力は{baise}に上がった！")
        myitem=giveitem()
        money=money+rolldice()*20
        print(f"あなたのお金は{money}")
        print("="*30)
        break
    enemy=ememyturn()
    if mos1<1:
      break
      return

#mos1=monsterHP()
print("=====サイコロRPGへようこそ=====")
baise=rolldice()
print(f"あなたの基礎攻撃力は{baise}です")
#playerhp=5
playerhp=rolldice()*10
print(f"あなたの基礎HPは{playerhp}です")
print(f"あなたのレベルは{count}です")
MP=rolldice()*2
print(f"あなたのMPは{MP}です")
print("="*30)
while True:
  start=input("それでは、冒険を開始しますか？(yes/はい)")
  if start=="yes" or start=="はい":
    mos1=monsterHP()
    print(f"敵が現れた！(HP:{mos1})")
    print("="*30)
    break
  else:
    print("yesかはいで答えてね")

battle=allturn()

if mos1<1:
  shopk=rolldice()
  if 1<=shopk<=6:
    print("ショップがあった！")
    shopp=shop()
    print(myitem)
    print("="*30)
  else:
   print()

mos1 = monsterHP()
print(f"新たな敵が現れた！(HP:{mos1})")
print("="*30)
battle=allturn()