# -*- coding: utf-8 -*-
"""サイコロRPG2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWMrJosJi5pCWlN67yL23FNxoINegCEB
"""

import random
import sys
count=1
def rolldice():
  return random.randint(1,6)
def attack(name,power):
  dice=rolldice()
  damege=power+dice
  return damege
def hantei(playerhp):
  if playerhp<=0:
    print("あなたは死んでしまった。")
    life=input("生き返りますか？(y/n):")
    if life=="y":
      print("生き返った！")
    elif life=="n":
      print("死んだ")
      sys.exit()
  return playerhp
#def giveitem():
  #item=rolldice()
  #if 1<=item<=3:
    #take=portion
    #print("超回復のポーションを手に入れた！")
  #else:
    #print("めっちゃ強い剣をゲットした！")

portion=200

mos1=30

print("=====サイコロRPGへようこそ=====")
baise=rolldice()
print(f"あなたの基礎攻撃力は{baise}です")
#playerhp=5
playerhp=rolldice()*10
print(f"あなたの基礎HPは{playerhp}です")
print(f"あなたのレベルは{count}です")
print("="*30)
while True:
  start=input("それでは、冒険を開始しますか？(yes/はい)")
  if start=="yes" or start=="はい":
    print("敵が現れた！")
    print("="*30)
    break
  else:
    print("yesかはいで答えてね")


while True:
  playerturn=int(input("何をする？（戦う(1)、回復(2)、逃げる(3)）"))

  if playerturn==2:
    if playerhp<=0:
      playerhp=playerhp+5*rocovary
    else:
      rocovary=rolldice()
      playerhp=playerhp+3+rocovary
    print(f"HPが{playerhp}になった！")

  elif playerturn==3:
    nigeru=rolldice()
    if 1<=nigeru<=3:
      print("逃げれなかった")
    else:
      print("逃げ切れた")
      print("="*30)
      break
  elif playerturn==1:
    damege=attack("player",baise)
    mos1=mos1-damege
    print(f"敵のHPは{mos1}")
    if mos1<=0:
      print("あなたの勝利！")
      print("="*30)
      count=count+1
      print(f"レベルが{count}に上がりました")
      baise=baise+rolldice()
      print(f"あなたの基礎攻撃力は{baise}に上がった！")
      break

  print("敵のターン")
  damege=attack("敵",2)
  playerhp=playerhp-damege
  print(f"あなたのHPは{playerhp}")
  print("="*30)
  if playerhp<=0:
    aiue=hantei(playerhp)
    print(aiue)