# -*- coding: utf-8 -*-
"""guess_the_number_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mcSzXbBNrJUIhtgzALawh-IOQqBkmv0
"""

import random
print("Guess the number!")
select=input("Chooce a game mode! hard or easy?--->")#difficulty setting
count=0
if select=="hard":#when its hard
  a=random.randint(1,1000)#randomly select a number between 1 and 1000
  while True:
    count=count+1#number of answers
    b=int(input("Guess the number"))#enter the numbers

    if a==b:
      print(f"It's a success on the {count} try!")#when you clear it
      break
    elif a>b:
      print("bigger")#when it was big
    elif a<b:
      print("smaller")#when it was small
elif select=="easy":
  a=random.randint(1,100)
  while True:
    count=count+1
    b=int(input("Guess the number"))

    if a==b:
      print(f"It's a success on the {count} try!")
      break
    elif a>b:
      print("bigger")
    elif a<b:
      print("smaller")