# -*- coding: utf-8 -*-
"""数字あてゲーム.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnKDSrtBItgjQrJs5dKX2r0NlKHR1xsJ
"""

import random
a=random.randint(1,100)#１から１００の中からランダムで数字を選ぶ
print("数字あてゲーム！")
count=0
while True:#繰り返し処理
  count=count+1
  b=int(input("数字を当てよう"))
  print(a)
  if a==b:
    print(f"やった{count}回で成功だ")
    break
  elif a>b:
    print("もっと大きい")
  elif a<b:
    print("もっと小さいよ")