# -*- coding: utf-8 -*-
"""リストの練習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPfTNqnQYStgyTzSSqj581w3ddfYF1iv
"""

a=["リンゴ","バナナ","ブドウ"]
a.append("みかん")
print(a)

#80以上の数字をピックアップするやつ
scores = [72, 85, 46, 92, 58, 80]
for i in scores:
  if i>=80:
    print(i)

#最大値をみつけるやつ
number=[10,20,30,40]
#マックスバリューというやつにナンバー（０）をいれる
max_value=number[0]
#numがマックスバリューより大きかったらマックスバリューをnumにする
for num in number:
  if num > max_value:
    max_value=num
print(max_value)

max_value=max(number)
print(max_value)

#ランダムで数字をだして最大値を出すやつ
import random
number=[]

for i in range(5):
  a=random.randint(1,200)
  number.append(a)
print(number)


maxv=number[0]
for num in number:
  if num>maxv:
    maxv=num
print(maxv)