# -*- coding: utf-8 -*-
"""辞書とかの練習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mwZWMrnNeqFgpYlRfoUyIboEUw09H84
"""

shopmenu={"薬草":10,"力の粉":20,"天の川の水":30,}
inventory={"剣":10,"盾":20,"アーマー":30}
mygold=30

print("買い物しよう")
select=input("アイテムを買いますか？(1)うりますか？(2)")
if select=="1":
  print("="*10,"menu","="*10)
  for item , price in shopmenu.items():
    print(f"{item},{price}")
  print("="*30)
  buy=(input("何を買いますか？アイテム名をいれてね:"))

  if buy in shopmenu:
    price=shopmenu[buy]
    if mygold>=price:
      mygold=mygold-price
      inventory[buy]=price
      print(f"{price}払って{buy}をかった")
      print("購入成功")

    else:
      print("金がたりねぇ")
  else:
    print("そんなアイテムないぜ")
  print("="*30)
  print(f"残りのお金は{mygold}です！")
  print(f"あなたのアイテムは{inventory}です！")

elif select=="2":
  print("="*10,"Item list","="*10)
  for soubi,price in inventory.items():
    print(f"{soubi},{price}")

  print("="*30)
  sell=input("なにを売りますか？アイテム名をいれてね")

  print("="*30)
  if sell in inventory:
    mygold=mygold+price
    inventory.pop(sell)

    print(f"手持ちのゴールドは{mygold}")
    print(f"あなたのアイテムは{inventory}")