# -*- coding: utf-8 -*-
"""Practicing 'def'

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wjk9kjG4i0iaWl-DOj6WmbSkWYzc4pCB
"""

def keisan(a,b):
  return a+b
keisan(1,5)

def great(name):
  print("こんにちは"+ name +"さん")
great("hinata")

def keisan(a,b):
  return a+b
keisan(8,4)

def money(syouhin,count):
  total=syouhin*count
  totaltax=total*1.1
  return totaltax
money(1000,2)